server:
  port: 8888
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: hospital
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai
start_time: "2023-03-11"
machine_id: "1"